export const FLOORS = [
  {
    id: "ground",
    name: "GROUND FLOOR",
    level: 0,
    modelId: 284870601,
    floorModelPath: "/groundfloor.glb",
    planModelPath: "/assets/PLANS GLB/Ground floor plans.compressed.glb",
  },
  {
    id: "first",
    name: "FIRST FLOOR",
    level: 1,
    modelId: 260826081,
    floorModelPath: "/firstfloor.glb",
    planModelPath: "/assets/PLANS GLB/First floor plans.compressed.glb",
  },
  {
    id: "second",
    name: "SECOND FLOOR",
    level: 2,
    modelId: 232878757,
    floorModelPath: "/secondfloor.glb",
    planModelPath: "/assets/PLANS GLB/First floor plans.compressed.glb",
  },
  {
    id: "third",
    name: "THIRD FLOOR",
    level: 3,
    modelId: 234125470,
    floorModelPath: "/thirdfloor.glb",
    planModelPath: "/assets/PLANS GLB/First floor plans.compressed.glb",
  },
  {
    id: "fourth",
    name: "FOURTH FLOOR",
    level: 4,
    modelId: 380523015,
    floorModelPath: "/fourthfloor.glb",
    planModelPath: "/assets/PLANS GLB/First floor plans.compressed.glb",
  },
  {
    id: "fifth",
    name: "FIFTH FLOOR",
    level: 5,
    modelId: 944343896,
    floorModelPath: "/fifthfloor.glb",
    planModelPath: "/assets/PLANS GLB/First floor plans.compressed.glb",
  },
  {
    id: "penthouse",
    name: "PENTHOUSE FLOOR",
    level: 6,
    modelId: 348634208,
    floorModelPath: "/penthousefloor.glb",
    planModelPath: "/assets/PLANS GLB/First floor plans.compressed.glb",
  },
  {
    id: "terrace",
    name: "TERRACE FLOOR",
    level: 7,
    modelId: 147987476,
    floorModelPath: "/teraacotta.glb",
    planModelPath: "/assets/PLANS GLB/flat-00.007.glb",
  },
]

  export const SPACE_DATA = {
    "flat-01001": {
      id: "LYMLIGHT-01",
      floor: 1,
      type: "LYMLIGHT",
      area: "63.30 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg",
        "/images/panoramas/LP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/l_back_101.jpg"
    },
    "flat-01.002": {
      id: "LYMLIGHT-02",
      floor: 2,
      type: "LYMLIGHT",
      area: "63.30 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg"
      ],
      floorPlanImage: "/images/floor-plans/l_back_201.jpg"
    },
    "flat-01003": {
      id: "LYMLIGHT-03",
      floor: 3,
      type: "LYMLIGHT",
      area: "63.30 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg"
      ],
      floorPlanImage: "/images/floor-plans/l_back_301.jpg"
    },
    // "flat-01004": {
    "TYPICAL_FLOOR_PLAN_(3RD,_4TH_)027": {
      id: "LYMLIGHT-04",
      floor: 4,
      type: "LYMLIGHT",
      area: "63.30 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg"
      ],
      floorPlanImage: "/images/floor-plans/l_back_401.jpg"
    },
    // "flat-01005": {
    "TYPICAL_FLOOR_PLAN_(2nd,_5TH_)027": {
      id: "LYMLIGHT-05",
      floor: 5,
      type: "LYMLIGHT",
      area: "63.30 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg"
      ],
      floorPlanImage: "/images/floor-plans/l_back_501.jpg"
    },
    "flat-01006": {
      id: "LYMLIGHT-06",
      floor: 6,
      type: "LYMLIGHT",
      area: "63.30 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg"
      ],
      floorPlanImage: "/images/floor-plans/l_back_601.jpg"
    },
    "Mesh001": {
    // "flat-00.007": {
      id: "GROUND FLOOR",
      floor: 0,
      type: "Ground Floor",
      area: "485.82 m²",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: "",
      render3D: "/images/3drenders/3dGroundFloor.png",
      roomImages: [
        "/images/floor-plans/GROUND.jpg",
      ],
      floorPlanImage: "/images/floor-plans/GROUND.jpg"
    },
    "TERRACE_FLOOR_PLAN": {
      id: "TERRACE",
      floor: 7,
      type: "TERRACE",
      area: "142.59 m²",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: "",
      render3D: "/images/3drenders/3dTerrace.png",
      roomImages: [
        "/images/floor-plans/floor_TERRACE FLOOR.PNG",
      ],
      floorPlanImage: "/images/floor-plans/floor_TERRACE FLOOR.PNG"
    },
    "flat-02001": {
      id: "LAVANDER-01",
      floor: 1,
      type: "LAVANDER",
      area: "65.52 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_back_102.jpg"
    },
    "flat-02002": {
      id: "LAVANDER-02",
      floor: 2,
      type: "LAVANDER",
      area: "65.52 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_back_202.jpg"
    },
    "flat-02003": {
      id: "LAVANDER-03",
      floor: 3,
      type: "LAVANDER",
      area: "65.52 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_back_302.jpg"
    },
    "flat-02004": {
      id: "LAVANDER-04",
      floor: 4,
      type: "LAVANDER",
      area: "65.52 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_back_402.jpg"
    },
    "flat-02005": {
      id: "LAVANDER-05",
      floor: 5,
      type: "LAVANDER",
      area: "65.52 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_back_502.jpg"
    },
    "flat-02006": {
      id: "LAVANDER-06",
      floor: 6,
      type: "LAVANDER",
      area: "65.52 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_back_602.jpg"
    },
    // "flat-03001": {
    "FirstFloor012": {

      id: "TEERACOTTA-01",
      floor: 1,
      type: "TEERACOTTA",
      area: "69.28 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_back_103.jpg"
    },
    "flat-03002": {
      id: "TEERACOTTA-02",
      floor: 2,
      type: "TEERACOTTA",
      area: "69.28 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_back_203.jpg"
    },
    // "flat-03003": {
   "TYPICAL_FLOOR_PLAN_(3RD,_4TH_)024": {
      id: "TEERACOTTA-03",
      floor: 3,
      type: "TEERACOTTA",
      area: "69.28 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_back_303.jpg"
    },
    "flat-03004": {
      id: "TEERACOTTA-04",
      floor: 4,
      type: "TEERACOTTA",
      area: "69.28 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_back_403.jpg"
    },
    "flat-03005": {
      id: "TEERACOTTA-05",
      floor: 5,
      type: "TEERACOTTA",
      area: "69.28 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_back_503.jpg"
    },
    // "flat-03006": {
    "PENTHOUSE__FLOOR_PLAN012": {
      id: "TEERACOTTA-06",
      floor: 6,
      type: "TEERACOTTA",
      area: "69.28 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_back_603.jpg"
    },
    "flat-04001": {
      id: "TEERACOTTA-07",
      floor: 1,
      type: "TEERACOTTA",
      area: "72.22 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_front_104.jpg"
    },
    "flat-04002": {
      id: "TEERACOTTA-08",
      floor: 2,
      type: "TEERACOTTA",
      area: "72.22 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_front_204.jpg"
    },
    "flat-04003": {
      id: "TEERACOTTA-09",
      floor: 3,
      type: "TEERACOTTA",
      area: "72.22 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_front_304.jpg"
    },
    "flat-04004": {
      id: "TEERACOTTA-10",
      floor: 4,
      type: "TEERACOTTA",
      area: "72.22 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_front_404.jpg"
    },
    "flat-04005": {
      id: "TEERACOTTA-11",
      floor: 5,
      type: "TEERACOTTA",
      area: "72.22 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_front_504.jpg"
    },
    "flat-04006": {
      id: "TEERACOTTA-12",
      floor: 6,
      type: "TEERACOTTA",
      area: "72.22 m²",
      masterRoomArea: "14.419 m²",
      masterBathroomArea: "4.680 m²",
      lobbyArea: "2.641 m²",
      kitchenArea: "7.539 m²",
      balconyArea: "2.000 m²",
      livingArea: "19.359 m²",
      storeArea: "1.530 m²",
      livingBathArea: "2.280 m²",
      laundryArea: "1.400 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
// "/images/Gallery/T(1).jpg",
        "/images/Gallery/T(2).jpg",
        "/images/Gallery/T(3).jpg",
        "/images/Gallery/T(4).jpg",
        "/images/Gallery/T(5).jpg",
        "/images/Gallery/T(6).jpg",
        "/images/Gallery/T(7).jpg",
        "/images/Gallery/T(8).jpg",
        "/images/Gallery/T(9).jpg",
        "/images/Gallery/T(10).jpg",
        "/images/Gallery/T(11).jpg"
      ],
      panoramas: [
        "/images/panoramas/TP(1).jpg",
        "/images/panoramas/TP(2).jpg",
        "/images/panoramas/TP(3).jpg",
        "/images/panoramas/TP(4).jpg",
        "/images/panoramas/TP(5).jpg",
        "/images/panoramas/TP(6).jpg"
      ],
      floorPlanImage: "/images/floor-plans/ter_front_604.jpg"
    },
    "flat-05001": {
      id: "LAVANDER-07",
      floor: 1,
      type: "LAVANDER",
      area: "70.70 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_front_105.jpg"
    },
    "flat-05002": {
      id: "LAVANDER-08",
      floor: 2,
      type: "LAVANDER",
      area: "70.70 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_front_205.jpg"
    },
    "flat-05003": {
      id: "LAVANDER-09",
      floor: 3,
      type: "LAVANDER",
      area: "70.70 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_front_305.jpg"
    },
    "flat-05004": {
      id: "LAVANDER-10",
      floor: 4,
      type: "LAVANDER",
      area: "70.70 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_front_405.jpg"
    },
    "flat-05005": {
      id: "LAVANDER-11",
      floor: 5,
      type: "LAVANDER",
      area: "70.70 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_front_505.jpg"
    },
    "flat-05006": {
      id: "LAVANDER-12",
      floor: 6,
      type: "LAVANDER",
      area: "70.70 m²",
      masterRoomArea: "13.596 m²",
      masterBathroomArea: "4.231 m²",
      lobbyArea: "3.601 m²",
      kitchenArea: "7.780 m²",
      balconyArea: "1.800 m²",
      livingArea: "16.481 m²",
      storeArea: "4.560 m²",
      livingBathArea: "2.850 m²",
      laundryArea: "2.499 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/La(1).jpg",
        "/images/Gallery/La(2).jpg",
        "/images/Gallery/La(3).jpg",
        "/images/Gallery/La(4).jpg",
        "/images/Gallery/La(5).jpg",
        "/images/Gallery/La(6).jpg",
        "/images/Gallery/La(7).jpg",
        "/images/Gallery/La(8).jpg",
        "/images/Gallery/La(9).jpg",
        "/images/Gallery/La(10).jpg",
        "/images/Gallery/La(11).jpg",
        "/images/Gallery/La(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
        "/images/panoramas/LaP(7).jpg"
      ],
      floorPlanImage: "/images/floor-plans/la_front_605.jpg"
    },
"flat-06001": {
      id: "LYMLIGHT-07",
      floor: 1,
      type: "LYMLIGHT",
      area: "65.26 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LaP(1).jpg",
        "/images/panoramas/LaP(2).jpg",
        "/images/panoramas/LaP(3).jpg",
        "/images/panoramas/LaP(4).jpg",
        "/images/panoramas/LaP(5).jpg",
        "/images/panoramas/LaP(6).jpg",
      ],
      floorPlanImage: "/images/floor-plans/l_front_106.jpg"
    },
    "flat-06002": {
      id: "LYMLIGHT-08",
      floor: 2,
      type: "LYMLIGHT",
      area: "65.26 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg",
        "/images/panoramas/LP(6).jpg",
      ],
      floorPlanImage: "/images/floor-plans/l_front_206.jpg"
    },
    "flat-06003": {
      id: "LYMLIGHT-09",
      floor: 3,
      type: "LYMLIGHT",
      area: "65.26 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg",
        "/images/panoramas/LP(6).jpg",
      ],
      floorPlanImage: "/images/floor-plans/l_front_306.jpg"
    },
    "flat-06004": {
      id: "LYMLIGHT-10",
      floor: 4,
      type: "LYMLIGHT",
      area: "65.26 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg",
        "/images/panoramas/LP(6).jpg",
      ],
      floorPlanImage: "/images/floor-plans/l_front_406.jpg"
    },
    "flat-06005": {
      id: "LYMLIGHT-11",
      floor: 5,
      type: "LYMLIGHT",
      area: "65.26 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg",
        "/images/panoramas/LP(6).jpg",
      ],
      floorPlanImage: "/images/floor-plans/l_front_506.jpg"
    },
    "flat-06006": {
      id: "LYMLIGHT-12",
      floor: 6,
      type: "LYMLIGHT",
      area: "65.26 m²",
      masterRoomArea: "12.304 m²",
      masterBathroomArea: " 4.481 m²",
      lobbyArea: "3.119 m²",
      kitchenArea: "5.606 m²",
      balconyArea: "1.960 m²",
      livingArea: "15.646 m²",
      storeArea: "2.162 m²",
      livingBathArea: "3.062 m²",
      laundryArea: "1.800 m²",
      render3D: "/images/3drenders/3dMiddleFloors.png",
      roomImages: [
        "/images/Gallery/L(1).jpg",
        "/images/Gallery/L(2).jpg",
        "/images/Gallery/L(3).jpg",

        "/images/Gallery/L(5).jpg",
        "/images/Gallery/L(6).jpg",
        "/images/Gallery/L(7).jpg",
        "/images/Gallery/L(8).jpg",
        "/images/Gallery/L(9).jpg",
        "/images/Gallery/L(10).jpg",
        "/images/Gallery/L(11).jpg",
        "/images/Gallery/L(12).jpg"
      ],
      panoramas: [
        "/images/panoramas/LP(1).jpg",
        "/images/panoramas/LP(2).jpg",
        "/images/panoramas/LP(3).jpg",
        "/images/panoramas/LP(4).jpg",
        "/images/panoramas/LP(5).jpg",
        "/images/panoramas/LP(6).jpg",
      ],
      floorPlanImage: "/images/floor-plans/l_front_606.jpg"
    },
      "SHOP-01.000": {
        id: "SHOP-01",
        floor: 0,
        type: "SHOP",
        area: "53 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "SHOP-02.000": {
        id: "SHOP-02",
        floor: 0,
        type: "SHOP",
        area: "46.8 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "SHOP-03.000": {
        id: "SHOP-03",
        floor: 0,
        type: "SHOP",
        area: "43.68 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "SHOP-04.000": {
        id: "SHOP-04",
        floor: 0,
        type: "SHOP",
        area: "43.68 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "SHOP-05.000": {
        id: "SHOP-05",
        floor: 0,
        type: "SHOP",
        area: "53.04 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "SHOP-06.000": {
        id: "SHOP-06",
        floor: 0,
        type: "SHOP",
        area: "53.04 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
        
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "SHOP-07.000": {
        id: "SHOP-07",
        floor: 0,
        type: "SHOP",
        area: "53.04 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "SHOP-08.000": {
        id: "SHOP-08",
        floor: 0,
        type: "SHOP",
        area: "15.64 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
      
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "LOBBY.000": {
        id: "LOBBY",
        floor: 0,
        type: "LOBBY",
        area:"2.64 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
      
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "ENTRANCE.000": {
        id: "ENTRANCE",
        floor: 0,
        type: "ENTRANCE",
        area: "2.86 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "ENTRANCE0.000": {
        id: "ENTRANCE0",
        floor: 0,
        type: "ENTRANCE",
        area: "2.88 m²",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: "",
      
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
      "ENT LOBBY.000": {
        id: "ENT LOBBY",
        floor: 0,
        type: "ENTRANCE LOBBY",
        area: "-",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
      
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      }, "HALL WAY.000": {
          id: "HALL WAY-G",
          floor: 0,
          type: "HALLWAY",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
      
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
          },
        "HALL WAY.001": {
          id: "HALL WAY-1",
          floor: 1,
          type: "HALLWAY",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
        },
        "HALL WAY.002": {
          id: "HALL WAY-2",
          floor: 2,
          type: "HALLAWY",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
        "HALL WAY.003": {
          id: "HALL WAY-3",
          floor: 3,
          type: "HALLWAY",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
      
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
          },
        "HALL WAY.004": {
          id: "HALL WAY-4",
          floor: 4,
          type: "HALLWAY",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
        
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
        },
        "HALL WAY.005": {
          id: "HALL WAY-5",
          floor: 5,
          type: "HALLWAY",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
        
        render3D: "/images/3drenders/3dGroundFloor.png",
        roomImages: [
          "/images/floor-plans/floor_GROUNDFLOOR.PNG",
        ],
        panoramas: [""
        ],
        floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
      },
        "HALL WAY.006": {
          id: "HALL WAY-6",
          floor: 6,
          type: "HALLWAY",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
      
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
          },
        "ELECTRICAL RM.000": {
          id: "ELECTRICAL RM",
          floor: 0,
          type: "Utility",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
        
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
        },
        "GUARD ROOM.000": {
          id: "GUARD ROOM",
          floor: 0,
          type: "Security",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
        
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
        },
        "GARBAGE.000": {
          id: "GARBAGE",
          floor: 0,
          type: "Utility",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
        
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
        },
        "TELECOM.000": {
          id: "TELECOM",
          floor: 0,
          type: "Utility",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
        
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
        },
        "GROUND1.000": {
          id: "GROUND1",
          floor: 0,
          type: "Common Area",
          area: "-",
          masterRoomArea: "",
          masterBathroomArea: "",
          lobbyArea: "",
          kitchenArea: "",
          balconyArea: "",
          livingArea: "",
          storeArea: "",
          livingBathArea: "",
          laundryArea: "",
        
          render3D: "/images/3drenders/3dGroundFloor.png",
          roomImages: [
            "/images/floor-plans/floor_GROUNDFLOOR.PNG",
          ],
          panoramas: [""
          ],
          floorPlanImage: "/images/floor-plans/floor_GROUNDFLOOR.PNG"
        },
    }

export type Room = {
  id: string;
  floor: number;
  type: string;
  area: string;
  status: string;
  objectName: string;
  floorPlanImage: string;
  roomImages: string[];
  panoramas: string[];
};

// interface RoomViewerModalProps {
//   room: Room;
//   isOpen: boolean;
//   onClose: () => void;
//   onToggleFavorite: (room: Room) => void;
//   onRemoveFavorite: (room: Room) => void
//   favoriteRooms: Room[];
// }

interface ComparisonModalProps {
  rooms: Room[]
  isOpen: boolean
  onClose: () => void
  onRemoveFavorite: (room: Room) => void
  onToggleFavorite: (room: Room) => void;
}