import { Ruler } from "lucide-react"

export const SPACE_DATA = {
  "flat-01001": {
    id: "01.001",
    floor: 1,
    type: "2BHK",
    area: "850 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: "",
    roomImages: [
      "/images/rooms/floor_01/room_01001_1.jpg",
      "/images/rooms/floor_01/room_01001_2.jpg",
      "/images/rooms/floor_01/room_01001_3.jpg"
    ],
    panoramas: [
      "/images/panoramas/floor_01/room_01001_living.jpg",
      "/images/panoramas/floor_01/room_01001_bedroom.jpg",
      "/images/panoramas/floor_01/room_01001_kitchen.jpg"
    ],
    floorPlanImage: "/images/floor-plans/floor_01/room_01001_plan.jpg"
  },
  "flat-01.002": {
    id: "01.002",
    floor: 1,
    type: "1BHK",
    area: "650 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: "",
    roomImages: [
      "/images/rooms/floor_01/room_01002_1.jpg",
      "/images/rooms/floor_01/room_01002_2.jpg"
    ],
    panoramas: [
      "/images/panoramas/floor_01/room_01002_living.jpg",
      "/images/panoramas/floor_01/room_01002_bedroom.jpg"
    ],
    floorPlanImage: "/images/floor-plans/floor_01/room_01002_plan.jpg"
  },
  "flat-01.003": {
    id: "01.003",
    floor: 1,
    type: "3BHK",
    area: "1100 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-01.004": {
    id: "01.004",
    floor: 1,
    type: "2BHK",
    area: "850 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-01.005": {
    id: "01.005",
    floor: 1,
    type: "1BHK",
    area: "650 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-01.006": {
    id: "01.006",
    floor: 1,
    type: "3BHK",
    area: "1100 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-01.007": {
    id: "01.007",
    floor: 1,
    type: "2BHK",
    area: "900 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-02001": {
    id: "02.001",
    floor: 2,
    type: "2BHK",
    area: "850 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-02.002": {
    id: "02.002",
    floor: 2,
    type: "1BHK",
    area: "650 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-02.003": {
    id: "02.003",
    floor: 2,
    type: "3BHK",
    area: "1100 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-02.004": {
    id: "02.004",
    floor: 2,
    type: "2BHK",
    area: "850 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-02.005": {
    id: "02.005",
    floor: 2,
    type: "1BHK",
    area: "650 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-02.006": {
    id: "02.006",
    floor: 2,
    type: "3BHK",
    area: "1100 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "FirstFloor012": {
    id: "03.001",
    floor: 3,
    type: "2BHK",
    area: "850 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-03.002": {
    id: "03.002",
    floor: 3,
    type: "1BHK",
    area: "650 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
  "flat-03.003": {
    id: "03.003",
    floor: 3,
    type: "3BHK",
    area: "1100 sq ft",
    masterRoomArea: "",
    masterBathroomArea: "",
    lobbyArea: "",
    kitchenArea: "",
    balconyArea: "",
    livingArea: "",
    storeArea: "",
    livingBathArea: "",
    laundryArea: ""
  },
    "SHOP-01.000": {
      id: "SHOP-01",
      floor: 0,
      type: "Retail Space",
      area: "450 sq ft",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: "",
      roomImages: [
        "/images/rooms/floor_00/shop_01_1.jpg",
        "/images/rooms/floor_00/shop_01_2.jpg"
      ],
      panoramas: [
        "/images/panoramas/floor_00/shop_01_main.jpg",
        "/images/panoramas/floor_00/shop_01_storage.jpg"
      ],
      floorPlanImage: "/images/floor-plans/floor_00/shop_01_plan.jpg"
    },
    "SHOP-02.000": {
      id: "SHOP-02",
      floor: 0,
      type: "Retail Space",
      area: "500 sq ft",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "SHOP-03.000": {
      id: "SHOP-03",
      floor: 0,
      type: "Retail Space",
      area: "520 sq ft",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "SHOP-04.000": {
      id: "SHOP-04",
      floor: 0,
      type: "Retail Space",
      area: "480 sq ft",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "SHOP-05.000": {
      id: "SHOP-05",
      floor: 0,
      type: "Retail Space",
      area: "550 sq ft",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "SHOP-06.000": {
      id: "SHOP-06",
      floor: 0,
      type: "Retail Space",
      area: "600 sq ft",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "SHOP-07.000": {
      id: "SHOP-07",
      floor: 0,
      type: "Retail Space",
      area: "500 sq ft",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "SHOP-08.000": {
      id: "SHOP-08",
      floor: 0,
      type: "Retail Space",
      area: "520 sq ft",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "LOBBY.000": {
      id: "LOBBY",
      floor: 0,
      type: "Common Area",
      description: "Main building lobby with reception and waiting area",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: "",
      roomImages: [
        "/images/rooms/floor_00/lobby_1.jpg",
        "/images/rooms/floor_00/lobby_2.jpg"
      ],
      panoramas: [
        "/images/panoramas/floor_00/lobby_main.jpg",
        "/images/panoramas/floor_00/lobby_reception.jpg"
      ],
      floorPlanImage: "/images/floor-plans/floor_00/lobby_plan.jpg"
    },
    "ENTRANCE.000": {
      id: "ENTRANCE",
      floor: 0,
      type: "Common Area",
      description: "Main entrance to the building",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "ENTRANCE0.000": {
      id: "ENTRANCE0",
      floor: 0,
      type: "Common Area",
      description: "Secondary entrance",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    },
    "ENT LOBBY.000": {
      id: "ENT LOBBY",
      floor: 0,
      type: "Common Area",
      description: "Entrance lobby area",
      masterRoomArea: "",
      masterBathroomArea: "",
      lobbyArea: "",
      kitchenArea: "",
      balconyArea: "",
      livingArea: "",
      storeArea: "",
      livingBathArea: "",
      laundryArea: ""
    }, "HALL WAY.000": {
        id: "HALL WAY-G",
        floor: 0,
        type: "Common Area",
        description: "Ground floor hallway",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "HALL WAY.001": {
        id: "HALL WAY-1",
        floor: 1,
        type: "Common Area",
        description: "First floor hallway",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "HALL WAY.002": {
        id: "HALL WAY-2",
        floor: 2,
        type: "Common Area",
        description: "Second floor hallway",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "HALL WAY.003": {
        id: "HALL WAY-3",
        floor: 3,
        type: "Common Area",
        description: "Third floor hallway",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "HALL WAY.004": {
        id: "HALL WAY-4",
        floor: 4,
        type: "Common Area",
        description: "Fourth floor hallway",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "HALL WAY.005": {
        id: "HALL WAY-5",
        floor: 5,
        type: "Common Area",
        description: "Fifth floor hallway",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "HALL WAY.006": {
        id: "HALL WAY-6",
        floor: 6,
        type: "Common Area",
        description: "Sixth floor hallway",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "ELECTRICAL RM.000": {
        id: "ELECTRICAL RM",
        floor: 0,
        type: "Utility",
        description: "Electrical room with main distribution panel",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "GUARD ROOM.000": {
        id: "GUARD ROOM",
        floor: 0,
        type: "Security",
        description: "24/7 security guard station",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "GARBAGE.000": {
        id: "GARBAGE",
        floor: 0,
        type: "Utility",
        description: "Waste management area",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "TELECOM.000": {
        id: "TELECOM",
        floor: 0,
        type: "Utility",
        description: "Telecommunications equipment room",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      },
      "GROUND1.000": {
        id: "GROUND1",
        floor: 0,
        type: "Common Area",
        description: "Ground floor common area",
        masterRoomArea: "",
        masterBathroomArea: "",
        lobbyArea: "",
        kitchenArea: "",
        balconyArea: "",
        livingArea: "",
        storeArea: "",
        livingBathArea: "",
        laundryArea: ""
      }
  }
  
